split things apart and hopefully make them saner

diff --git a/.github/workflows/auto-approve.yml b/.github/workflows/auto-approve.yml
--- a/.github/workflows/auto-approve.yml
+++ b/.github/workflows/auto-approve.yml
@@ -33,8 +33,14 @@ jobs:
             exit 78
           fi
 
+          changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
+          if [$? -ne 0 ]; then
+            echo "Failed to get diff"
+            exit 78
+          fi
+
           # check if PR touches files other than SOURCE_DATE_EPOCH
-          if [[ $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v SOURCE_DATE_EPOCH) ]] || [ $? -ne 0 ]; then
+          if [[ $(echo ${changes} | grep -v SOURCE_DATE_EPOCH) ]]; then
             echo "Not only SOURCE_DATE_EPOCH"
             exit 78
           fi
